[2021-03-29 23:14:29,242] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_0 2021-03-28T00:00:00+00:00 [queued]>
[2021-03-29 23:14:29,314] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_0 2021-03-28T00:00:00+00:00 [queued]>
[2021-03-29 23:14:29,321] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-29 23:14:29,324] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-29 23:14:29,326] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-29 23:14:29,415] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): runme_0> on 2021-03-28T00:00:00+00:00
[2021-03-29 23:14:29,426] {standard_task_runner.py:52} INFO - Started process 56 to run task
[2021-03-29 23:14:29,504] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_0', '2021-03-28T00:00:00+00:00', '--job-id', '11', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpsokp1mi0', '--error-file', '/tmp/tmpqraszyy8']
[2021-03-29 23:14:29,509] {standard_task_runner.py:77} INFO - Job 11: Subtask runme_0
[2021-03-29 23:14:29,748] {logging_mixin.py:104} INFO - Running <TaskInstance: example_bash_operator.runme_0 2021-03-28T00:00:00+00:00 [running]> on host 33dac7d1aa5e
[2021-03-29 23:14:29,924] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=runme_0
AIRFLOW_CTX_EXECUTION_DATE=2021-03-28T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-28T00:00:00+00:00
[2021-03-29 23:14:29,927] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-03-29 23:14:29,930] {bash.py:158} INFO - Running command: echo "example_bash_operator__runme_0__20210328" && sleep 1
[2021-03-29 23:14:29,949] {bash.py:169} INFO - Output:
[2021-03-29 23:14:29,952] {bash.py:173} INFO - example_bash_operator__runme_0__20210328
[2021-03-29 23:14:30,959] {bash.py:177} INFO - Command exited with return code 0
[2021-03-29 23:14:31,013] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=runme_0, execution_date=20210328T000000, start_date=20210329T231429, end_date=20210329T231431
[2021-03-29 23:14:31,056] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-29 23:14:31,093] {local_task_job.py:146} INFO - Task exited with return code 0
