[2021-04-14 13:28:32,511] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop 2021-03-30T00:00:00+00:00 [queued]>
[2021-04-14 13:28:32,563] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop 2021-03-30T00:00:00+00:00 [queued]>
[2021-04-14 13:28:32,566] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-14 13:28:32,569] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-04-14 13:28:32,577] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-14 13:28:32,655] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): run_after_loop> on 2021-03-30T00:00:00+00:00
[2021-04-14 13:28:32,668] {standard_task_runner.py:52} INFO - Started process 92 to run task
[2021-04-14 13:28:32,679] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'run_after_loop', '2021-03-30T00:00:00+00:00', '--job-id', '38', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpq0hblbr6', '--error-file', '/tmp/tmprh1yogf2']
[2021-04-14 13:28:32,680] {standard_task_runner.py:77} INFO - Job 38: Subtask run_after_loop
[2021-04-14 13:28:32,926] {logging_mixin.py:104} INFO - Running <TaskInstance: example_bash_operator.run_after_loop 2021-03-30T00:00:00+00:00 [running]> on host 33dac7d1aa5e
[2021-04-14 13:28:33,237] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=run_after_loop
AIRFLOW_CTX_EXECUTION_DATE=2021-03-30T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-30T00:00:00+00:00
[2021-04-14 13:28:33,253] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-14 13:28:33,266] {bash.py:158} INFO - Running command: echo 1
[2021-04-14 13:28:33,335] {bash.py:169} INFO - Output:
[2021-04-14 13:28:33,372] {bash.py:173} INFO - 1
[2021-04-14 13:28:33,373] {bash.py:177} INFO - Command exited with return code 0
[2021-04-14 13:28:33,562] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=run_after_loop, execution_date=20210330T000000, start_date=20210414T132832, end_date=20210414T132833
[2021-04-14 13:28:33,833] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-04-14 13:28:33,915] {local_task_job.py:146} INFO - Task exited with return code 0
